### ISSUE TITLE
预编译合约根据用户地址获取私钥信息时的一个bug

### ISSUE THREAD

**Issue by sagexueqi** [WeBankFinTech/WeBASE-Front#241]
PrecompiledService中，getCredentials方法默认未使用aes加密。如果通过node-mgr创建私钥时的节点与执行预编译合约的Front不一致，会导致私钥无法解密。
原因：如果当前节点没有创建该账户，数据库中没有记录，会查询node-mgr。而node-mgr中存储的时aes加密后的私钥信息。导致解析失败。

**Comment by mingzhenliu** [comment]
前置PrecompiledService中，getCredentials创建的私钥只能在当前前置使用。如果需要在多个前置使用请使用nodemanager的私钥管理或者，把私钥导出再调入到其他需要使用该私钥的前置中去。
