### ISSUE TITLE
启动时报错node's ca.crt is not existed

### ISSUE THREAD

**Issue by CodingCattwo** [WeBankFinTech/WeBASE-Front#38]
报错信息为：
`node's ca.crt is not existed
nodeDir:/home/ubuntu/fisco/nodes/127.0.0.1/node0`

其中dist/conf/application.yml 中的nodeDir 配置为
`nodeDir:/home/ubuntu/fisco/nodes/127.0.0.1/node0`

dist/report/config.json也为
`nodeDir:/home/ubuntu/fisco/nodes/127.0.0.1/node0`

部署的链是单群组4节点，配置nodeDir时，
`/nodes/127.0.0.1`中有多个node，应该填哪一个？

**Comment by yanyanho** [comment]
任选一个即可。
