### ISSUE TITLE
WeBASE-Front启动报错

### ISSUE THREAD

**Issue by cxmqq333** [WeBankFinTech/WeBASE-Front#456]
按照文档https://webasedoc.readthedocs.io/zh_CN/latest/docs/WeBASE-Install/developer.html启动WeBASE-Front报错
Failed to connect to nodes: [ ssl handshake failed:/127.0.0.1:20200, The reasons for failure may be: 1. the configured certificate is not the same set of certificates as the node's certificate; 2. the configured certificate is not issued by the same authority as the node's certificate. Please refer to https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id24]

反复确认了，证书没错啊。从sdk目录下拷贝过来的

**Comment by ikechan8370** [comment]
遇到同样的问题。换了jdk版本也不行  自建链和一键部署的链也都不行。

**Comment by cxmqq333** [comment]
> 遇到同样的问题。换了jdk版本也不行 自建链和一键部署的链也都不行。

后来把日志级别调到debug，发现是Oracle jdk中的security的限制。sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1。
去掉jdk-xxx\jre\lib\security\java.security里面的"jdk.tls.disabledAlgorithms"里的"secp256k1"就行了。

**Comment by YvetteGwen** [comment]
@cxmqq333 请问你用的是哪个版本的jdk呢？遇到了同样的问题，使用的是oracle jdk 11, 并从jdk.tls.disabledAlgorithms里删掉了secp256k1也不行（参考了https://www.java.com/en/configure_crypto.html）

**Comment by CodingCattwo** [comment]
一部分jdk更新后，将k1曲线默认禁用了，可将front中的`lib`目录中的web3sdk 2.6.1替换为web3sdk 2.6.2，再尝试启动。最新版1.4.2已解决该问题

**Comment by 666-shr666** [comment]
请问front目录在哪里？
