### ISSUE TITLE
dist目录中找不到report

### ISSUE THREAD

**Issue by Jalins** [WeBankFinTech/WeBASE-Front#91]
使用gradle build -x test命令编译成功
![image](https://user-images.githubusercontent.com/31172582/58458048-b7ab3000-815a-11e9-8184-520c7199031e.png)
但是生成的dist目录中不存在report
![image](https://user-images.githubusercontent.com/31172582/58458121-f214cd00-815a-11e9-964a-add665d8ab33.png)

**Comment by mingzhenliu** [comment]
report在1.0的版本已经去掉了
